# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'проект7.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 462)
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(130, 160, 351, 231))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 51, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 50, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 50, 51, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(290, 50, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(360, 40, 61, 91))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(430, 50, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(490, 50, 51, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(550, 50, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Nasalization")
        font.setPointSize(72)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "К"))
        self.label_2.setText(_translate("Dialog", "А"))
        self.label_3.setText(_translate("Dialog", "Л"))
        self.label_4.setText(_translate("Dialog", "Е"))
        self.label_5.setText(_translate("Dialog", "Н"))
        self.label_6.setText(_translate("Dialog", "Д"))
        self.label_7.setText(_translate("Dialog", "А"))
        self.label_8.setText(_translate("Dialog", "Р"))
        self.label_9.setText(_translate("Dialog", "Ь"))


